import { StyleSheet } from 'react-native'
import { colors, spacing, radius, shadows, typography } from '../../theme'

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  listContent: {
    paddingVertical: spacing.sm,
    paddingTop: spacing.sm,
  },
  screenContent: {
    flex: 1,
    paddingTop: 96,
  },
  searchContainer: {
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
    marginTop: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchInput: {
    flex: 1,
    backgroundColor: colors.white,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius.sm,
    fontSize: 14,
    color: colors.textPrimary,
    elevation: 1,
  },
  searchClear: {
    marginLeft: spacing.sm,
    padding: spacing.xs,
    borderRadius: radius.sm,
    backgroundColor: 'transparent',
  },
  tabRow: {
    flexDirection: 'row',
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
    backgroundColor: colors.border,
    borderRadius: radius.md,
    padding: spacing.xs,
  },
  tabButton: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: radius.sm,
    alignItems: 'center',
  },
  tabButtonActive: {
    backgroundColor: colors.white,
  },
  tabText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  tabTextActive: {
    color: colors.textPrimary,
  },
  selectionBar: {
    marginHorizontal: spacing.md,
    marginBottom: spacing.sm,
    backgroundColor: colors.primaryLight,
    borderRadius: radius.md,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    elevation: 1,
  },
  selectionText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  selectionActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: spacing.sm,
  },
  selectionBtn: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.border,
    borderRadius: radius.sm,
  },
  selectionBtnDanger: {
    backgroundColor: colors.dangerLight,
  },
  selectionBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  selectionBtnTextDanger: {
    color: colors.danger,
  },
  selectionBtnGhost: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
  },
  selectionBtnGhostText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  toggleRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 96,
    marginBottom: spacing.sm,
  },
  toggleButton: {
    backgroundColor: colors.white,
    paddingVertical: spacing.sm,
    paddingHorizontal: 14,
    borderRadius: spacing.xl,
    marginHorizontal: spacing.xs,
    elevation: 1,
  },
  toggleActive: {
    backgroundColor: colors.primary,
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    backgroundColor: colors.white,
    marginHorizontal: spacing.md,
    borderRadius: radius.md,
    marginVertical: spacing.xs,
    elevation: 1,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    color: colors.textPrimary,
    fontWeight: '700',
    fontSize: 18,
  },
  content: {
    flex: 1,
    marginLeft: spacing.md,
    justifyContent: 'center',
  },
  rowTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  name: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
    flex: 1,
    marginRight: spacing.sm,
  },
  time: {
    fontSize: 12,
    color: colors.textMuted,
  },
  rowBottom: {
    marginTop: spacing.xs,
  },
  lastMessage: {
    fontSize: 13,
    color: colors.textSecondary,
  },
  divider: {
    height: 0,
  },
  emptyContainer: {
    marginTop: 140,
    alignItems: 'center',
  },
  emptyTitle: {
    color: colors.textMuted,
    fontSize: 16,
  },
  emptyUnreadContainer: {
    marginTop: 120,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyUnreadText: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  emptyAllContainer: {
    marginTop: 120,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyAllText: {
    marginTop: spacing.md,
    fontSize: 20,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  fab: {
    position: 'absolute',
    right: 18,
    bottom: 28,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
  },
  fabText: {
    color: colors.white,
    fontSize: 28,
    fontWeight: '700',
    marginTop: -2,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlay,
  },
  modalCard: {
    backgroundColor: colors.white,
    padding: spacing.lg,
    borderTopLeftRadius: radius.md,
    borderTopRightRadius: radius.md,
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: spacing.sm,
    color: colors.textPrimary,
  },
  modalInput: {
    backgroundColor: colors.background,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    fontSize: 14,
    color: colors.textPrimary,
  },
  modalError: {
    marginTop: spacing.xs,
    color: colors.danger,
    fontSize: 12,
  },
  modalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: spacing.md,
  },
  modalBtnGhost: {
    marginRight: spacing.md,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  modalBtnGhostText: {
    color: colors.textSecondary,
    fontWeight: '600',
  },
  modalBtnPrimary: {
    paddingVertical: spacing.sm,
    paddingHorizontal: 14,
    backgroundColor: colors.primary,
    borderRadius: radius.sm,
  },
  modalBtnPrimaryText: {
    color: colors.white,
    fontWeight: '700',
  },
})
