version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"